# Syntax
# name: Workflow_Name (Appears in UI)
# on: (Can be push/pull_request/workflow_dispatch)


name: Security Scans (SAST, SCA, Secrets)
on: 
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  
  # SAST (Static Application Security Testing)
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run SAST'
      - uses: .github/workflows/scans/sast.yml # Get the code
        run:
  
  # SCA (Software Composition Analysis - Dependency Scanning)
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run SCA'
      - uses: .github/workflows/scans/sca.yml
        run:
  
  # Secrets Scanning
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Secrets'
      - uses: .github/workflows/scans/secrets.yml
        run:
